version: 2.1
orbs:
  python: circleci/python@1.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11.0
    working_directory: /code
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          project-dir: /code 
      - run:
          name: Collect Static Files
          command: poetry run python manage.py collectstatic --noinput
      - run:
          name: Run Migrations
          command: poetry run python manage.py migrate
      - run:
          name: Run Linting
          command: poetry run flake8 --ignore=F841 
      - run:
          name: Run Tests
          command: poetry run python manage.py test
      - run:
          name: Coverage Report
          command: poetry run coverage report
      - run:
          name: Coverage HTML
          command: poetry run coverage html

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: curl -X POST $RENDER_WEBHOOK

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          name: Deploy to Render
          requires:
            - build
          filters:
            branches:
              only:
                - main
