version: 2.1
orbs :
  python: circleci/python@1.2.2

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1
    working_directory: ~/project
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          path: ~/project
          
      - run:
          name: Install Project Dependencies
          command: poetry install --only=main
      - run:
          name: Run Migrations
          command: poetry run python manage.py migrate
      - run:
          name: Run Tests
          command: poetry run python manage.py test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Deploy"
          command: curl -X POST $RENDER_WEBHOOK

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          name: Deploy to Render
          requires:
            - build
          filters:
            branches:
              only:
                - main
