version: 2.1
orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/python:3.12.1
    working_directory: ~/project
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Install Project Dependencies
          command: poetry install --only=main
      - run:
          name: Run Migrations
          command: poetry run python manage.py migrate
      - run:
          name: Run Tests
          command: poetry run python manage.py test
      - run:
          name: Coverage
          command: poetry run coverage run --source='.' manage.py test
      - run:
          name: Build and Push Docker Image
          command: |
            IMAGE_TAG=$DOCKERHUB_USERNAME/p13:$CIRCLE_BUILD_NUM
            docker build -t $IMAGE_TAG .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $IMAGE_TAG

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Pull and Deploy Docker Image
          command: |
            IMAGE_TAG=$DOCKERHUB_USERNAME/p13:$CIRCLE_BUILD_NUM
            docker pull $IMAGE_TAG
            curl -X POST $RENDER_WEBHOOK --data "image=$IMAGE_TAG"
    

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          name: Deploy to Render
          requires:
            - build
          filters:
            branches:
              only:
                - main
