version: 2.1
jobs:
  build:
    docker:
      - image: python:3.11
    working_directory: /code
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install poetry
      - run:
          name: Install Project Dependencies
          command: poetry install --only=main
      - run:
          name: Run Migrations
          command: poetry run python manage.py migrate
      - run:
          name: Run Tests
          command: poetry run python manage.py test
