version: 2.1
orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3

commands:
  setup_docker:
    description: "Setup Docker Environment"
    steps:
      - setup_remote_docker:
          version: 20.10.7

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
      - python/install-packages:
          pkg-manager: poetry
      - save_cache:
          paths:
            - ~/.cache/pypoetry
          key: v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          name: lint and format
          command: |
            poetry run black .
            poetry run flake8 . --ignore=F841
      - run:
          name: Test and Coverage
          command: |
            poetry run python manage.py migrate
            poetry run coverage run --source='.' manage.py test 
            poetry run coverage report
            poetry run coverage html

  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - attach_workspace:
          at: ~/project
      - setup_docker
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Ls files
          command: |
            ls -la .
            ls -R .

      - run:
          name: Build and Deploy
          command: |
            docker build -t tmee3/p13:1.0 ./
            docker push tmee3/p13:1.0
            curl -X POST $RENDER_WEBHOOK --data "image=tmee3/p13:1.0"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
