version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pyproject.toml" }}
      - run:
          name: Install Dependencies
          command: |
            pip install poetry
            poetry install
      - save_cache:
          paths:
            - ~/.cache/pypoetry
          key: v1-dependencies-{{ checksum "pyproject.toml" }}
      - run:
          name: Lint and Format
          command: |
            poetry run black .
            poetry run flake8 . --ignore=F841
      - run:
          name: Test and Coverage
          command: |
            poetry run python manage.py migrate
            poetry run coverage run --source='.' manage.py test 
            poetry run coverage report
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/p13:1.0 ./
            docker push $DOCKERHUB_USERNAME/p13:1.0
      - run:
          name: Deploy
          command: |
            curl -X POST $RENDER_WEBHOOK --data "image=$DOCKERHUB_USERNAME/p13:1.0"

workflows:
  version: 2
  all-in-one:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
