# Generated by Django 5.0 on 2023-12-06 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "oc_lettings_site",
            "0002_remove_letting_address_delete_address_delete_letting",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Profile",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Profile",
                    table="profiles_profile",
                ),
            ],
        )
    ]
